### ISSUE TITLE
Rate limit exception is raised outside of rate limiting window

### ISSUE THREAD

**Issue by otterbotter** [anvilco/python-anvil#11]
Hi! 

I'm running a script to generate PDFs for a long list of invoices (about 900 in total) and getting the below exception:

```
File "../lib/python3.8/site-packages/python_anvil/api.py", line 72, in fill_pdf
    return api.post(
  File "../lib/python3.8/site-packages/python_anvil/api_resources/requests.py", line 80, in post
    content, status_code, headers = self._client.request(
  File "../lib/python3.8/site-packages/ratelimit/decorators.py", line 77, in wrapper
    raise RateLimitException('too many calls', period_remaining)
ratelimit.exception.RateLimitException: too many calls
```

I've tried twice, once with a 5 second sleep between each hit to the Anvil API and another attempt with a 10 second sleep to make sure I don't fall within the rate limiting window [as per the docs](https://www.useanvil.com/docs/api/fill-pdf#rate-limits) but it still fails, which is super odd! 

I'm requesting your help since I've already generated 400 PDFs I didn't need and want to avoid wasting more money by re-running the script :)

I've not dug into the code so it is possible that this is not an error with the API client and is coming from the Anvil server.

**Comment by aalmazan** [comment]
Hey @otterbotter, thanks for taking the time for writing the report. I'll be taking a look at this shortly.

Also a reminder: we (Anvil) have developer tokens in the same place where you got your production token. Those dev tokens will not count towards your API usage (will be free), so please use those until your ready for the real thing, especially with 400 test PDFs!

**Comment by otterbotter** [comment]
Hi @aalmazan, thanks very much for the feedback.

I do use development tokens for local development and we have had this system running in production for a long time. 

I am now trying to run a once-off script in production which is working with the same code but a larger batch than usual and this is where I am running into this rate limiting error. I thought adding the sleep between PDF fillings would immediately fix it which is why I tried again in production :)

Sorry for not including more info in the issue description. I'll try to replicate the error locally and check if I can see anything wrong.

**Comment by otterbotter** [comment]
@aalmazan I've written a quick script to test this bug locally. Here is log output using the development key. No sleep between requests in this script.

I see the same error as I did in the production key: the rate limiting always stops the script at 200 regardless of how long it took to reach 200.

Note the start time is 08:47:35 and it stopped at 08:52:29

```
[2021-07-30 08:47:35.486042+00:00] Filled 1/1000 PDFs
[2021-07-30 08:47:36.904468+00:00] Filled 2/1000 PDFs
[2021-07-30 08:47:38.525230+00:00] Filled 3/1000 PDFs
[2021-07-30 08:47:39.692759+00:00] Filled 4/1000 PDFs
[2021-07-30 08:47:41.168608+00:00] Filled 5/1000 PDFs
[2021-07-30 08:47:42.667425+00:00] Filled 6/1000 PDFs
[2021-07-30 08:47:44.282120+00:00] Filled 7/1000 PDFs
[2021-07-30 08:47:45.900293+00:00] Filled 8/1000 PDFs
[2021-07-30 08:47:47.073086+00:00] Filled 9/1000 PDFs
[2021-07-30 08:47:48.443244+00:00] Filled 10/1000 PDFs
[2021-07-30 08:47:49.908640+00:00] Filled 11/1000 PDFs
[2021-07-30 08:47:51.394153+00:00] Filled 12/1000 PDFs
[2021-07-30 08:47:53.192917+00:00] Filled 13/1000 PDFs
[2021-07-30 08:47:54.731618+00:00] Filled 14/1000 PDFs
[2021-07-30 08:47:56.123803+00:00] Filled 15/1000 PDFs
[2021-07-30 08:47:57.333156+00:00] Filled 16/1000 PDFs
[2021-07-30 08:47:58.784578+00:00] Filled 17/1000 PDFs
[2021-07-30 08:48:00.302701+00:00] Filled 18/1000 PDFs
[2021-07-30 08:48:01.679903+00:00] Filled 19/1000 PDFs
[2021-07-30 08:48:03.183357+00:00] Filled 20/1000 PDFs
[2021-07-30 08:48:04.294545+00:00] Filled 21/1000 PDFs
[2021-07-30 08:48:05.727010+00:00] Filled 22/1000 PDFs
[2021-07-30 08:48:06.999078+00:00] Filled 23/1000 PDFs
[2021-07-30 08:48:08.313021+00:00] Filled 24/1000 PDFs
[2021-07-30 08:48:09.573556+00:00] Filled 25/1000 PDFs
[2021-07-30 08:48:10.684879+00:00] Filled 26/1000 PDFs
[2021-07-30 08:48:12.565686+00:00] Filled 27/1000 PDFs
[2021-07-30 08:48:14.882067+00:00] Filled 28/1000 PDFs
[2021-07-30 08:48:16.253494+00:00] Filled 29/1000 PDFs
[2021-07-30 08:48:17.764543+00:00] Filled 30/1000 PDFs
[2021-07-30 08:48:19.022252+00:00] Filled 31/1000 PDFs
[2021-07-30 08:48:20.460446+00:00] Filled 32/1000 PDFs
[2021-07-30 08:48:21.991665+00:00] Filled 33/1000 PDFs
[2021-07-30 08:48:23.452405+00:00] Filled 34/1000 PDFs
[2021-07-30 08:48:24.963690+00:00] Filled 35/1000 PDFs
[2021-07-30 08:48:26.672527+00:00] Filled 36/1000 PDFs
[2021-07-30 08:48:28.235792+00:00] Filled 37/1000 PDFs
[2021-07-30 08:48:29.861038+00:00] Filled 38/1000 PDFs
[2021-07-30 08:48:31.478145+00:00] Filled 39/1000 PDFs
[2021-07-30 08:48:33.063414+00:00] Filled 40/1000 PDFs
[2021-07-30 08:48:34.593038+00:00] Filled 41/1000 PDFs
[2021-07-30 08:48:36.149330+00:00] Filled 42/1000 PDFs
[2021-07-30 08:48:37.670656+00:00] Filled 43/1000 PDFs
[2021-07-30 08:48:39.496720+00:00] Filled 44/1000 PDFs
[2021-07-30 08:48:41.208084+00:00] Filled 45/1000 PDFs
[2021-07-30 08:48:42.714434+00:00] Filled 46/1000 PDFs
[2021-07-30 08:48:44.313414+00:00] Filled 47/1000 PDFs
[2021-07-30 08:48:45.838032+00:00] Filled 48/1000 PDFs
[2021-07-30 08:48:47.729906+00:00] Filled 49/1000 PDFs
[2021-07-30 08:48:48.991224+00:00] Filled 50/1000 PDFs
[2021-07-30 08:48:50.091080+00:00] Filled 51/1000 PDFs
[2021-07-30 08:48:52.283424+00:00] Filled 52/1000 PDFs
[2021-07-30 08:48:53.782839+00:00] Filled 53/1000 PDFs
[2021-07-30 08:48:55.830641+00:00] Filled 54/1000 PDFs
[2021-07-30 08:48:57.291421+00:00] Filled 55/1000 PDFs
[2021-07-30 08:48:58.636100+00:00] Filled 56/1000 PDFs
[2021-07-30 08:48:59.970817+00:00] Filled 57/1000 PDFs
[2021-07-30 08:49:01.095391+00:00] Filled 58/1000 PDFs
[2021-07-30 08:49:02.587142+00:00] Filled 59/1000 PDFs
[2021-07-30 08:49:04.378712+00:00] Filled 60/1000 PDFs
[2021-07-30 08:49:05.639389+00:00] Filled 61/1000 PDFs
[2021-07-30 08:49:07.183430+00:00] Filled 62/1000 PDFs
[2021-07-30 08:49:08.249727+00:00] Filled 63/1000 PDFs
[2021-07-30 08:49:09.717240+00:00] Filled 64/1000 PDFs
[2021-07-30 08:49:11.714443+00:00] Filled 65/1000 PDFs
[2021-07-30 08:49:13.201054+00:00] Filled 66/1000 PDFs
[2021-07-30 08:49:15.273036+00:00] Filled 67/1000 PDFs
[2021-07-30 08:49:16.362319+00:00] Filled 68/1000 PDFs
[2021-07-30 08:49:17.612926+00:00] Filled 69/1000 PDFs
[2021-07-30 08:49:19.054069+00:00] Filled 70/1000 PDFs
[2021-07-30 08:49:20.671108+00:00] Filled 71/1000 PDFs
[2021-07-30 08:49:22.116886+00:00] Filled 72/1000 PDFs
[2021-07-30 08:49:23.650308+00:00] Filled 73/1000 PDFs
[2021-07-30 08:49:25.532032+00:00] Filled 74/1000 PDFs
[2021-07-30 08:49:27.162190+00:00] Filled 75/1000 PDFs
[2021-07-30 08:49:28.708927+00:00] Filled 76/1000 PDFs
[2021-07-30 08:49:30.445389+00:00] Filled 77/1000 PDFs
[2021-07-30 08:49:32.059317+00:00] Filled 78/1000 PDFs
[2021-07-30 08:49:33.311121+00:00] Filled 79/1000 PDFs
[2021-07-30 08:49:34.887829+00:00] Filled 80/1000 PDFs
[2021-07-30 08:49:36.024096+00:00] Filled 81/1000 PDFs
[2021-07-30 08:49:37.536562+00:00] Filled 82/1000 PDFs
[2021-07-30 08:49:39.030725+00:00] Filled 83/1000 PDFs
[2021-07-30 08:49:40.253518+00:00] Filled 84/1000 PDFs
[2021-07-30 08:49:41.397522+00:00] Filled 85/1000 PDFs
[2021-07-30 08:49:42.843043+00:00] Filled 86/1000 PDFs
[2021-07-30 08:49:44.032410+00:00] Filled 87/1000 PDFs
[2021-07-30 08:49:45.536223+00:00] Filled 88/1000 PDFs
[2021-07-30 08:49:46.792314+00:00] Filled 89/1000 PDFs
[2021-07-30 08:49:48.303466+00:00] Filled 90/1000 PDFs
[2021-07-30 08:49:49.837088+00:00] Filled 91/1000 PDFs
[2021-07-30 08:49:51.092170+00:00] Filled 92/1000 PDFs
[2021-07-30 08:49:52.644130+00:00] Filled 93/1000 PDFs
[2021-07-30 08:49:54.330840+00:00] Filled 94/1000 PDFs
[2021-07-30 08:49:55.859575+00:00] Filled 95/1000 PDFs
[2021-07-30 08:49:57.390433+00:00] Filled 96/1000 PDFs
[2021-07-30 08:49:58.678173+00:00] Filled 97/1000 PDFs
[2021-07-30 08:50:00.182263+00:00] Filled 98/1000 PDFs
[2021-07-30 08:50:01.743729+00:00] Filled 99/1000 PDFs
[2021-07-30 08:50:03.079897+00:00] Filled 100/1000 PDFs
[2021-07-30 08:50:04.886628+00:00] Filled 101/1000 PDFs
[2021-07-30 08:50:06.405275+00:00] Filled 102/1000 PDFs
[2021-07-30 08:50:08.777975+00:00] Filled 103/1000 PDFs
[2021-07-30 08:50:10.273023+00:00] Filled 104/1000 PDFs
[2021-07-30 08:50:11.643284+00:00] Filled 105/1000 PDFs
[2021-07-30 08:50:13.053413+00:00] Filled 106/1000 PDFs
[2021-07-30 08:50:14.496306+00:00] Filled 107/1000 PDFs
[2021-07-30 08:50:16.018125+00:00] Filled 108/1000 PDFs
[2021-07-30 08:50:17.191659+00:00] Filled 109/1000 PDFs
[2021-07-30 08:50:18.280847+00:00] Filled 110/1000 PDFs
[2021-07-30 08:50:19.459420+00:00] Filled 111/1000 PDFs
[2021-07-30 08:50:20.965997+00:00] Filled 112/1000 PDFs
[2021-07-30 08:50:22.423973+00:00] Filled 113/1000 PDFs
[2021-07-30 08:50:24.839586+00:00] Filled 114/1000 PDFs
[2021-07-30 08:50:26.385415+00:00] Filled 115/1000 PDFs
[2021-07-30 08:50:27.770451+00:00] Filled 116/1000 PDFs
[2021-07-30 08:50:29.169522+00:00] Filled 117/1000 PDFs
[2021-07-30 08:50:30.241785+00:00] Filled 118/1000 PDFs
[2021-07-30 08:50:31.360578+00:00] Filled 119/1000 PDFs
[2021-07-30 08:50:33.120937+00:00] Filled 120/1000 PDFs
[2021-07-30 08:50:34.560482+00:00] Filled 121/1000 PDFs
[2021-07-30 08:50:36.000027+00:00] Filled 122/1000 PDFs
[2021-07-30 08:50:37.116172+00:00] Filled 123/1000 PDFs
[2021-07-30 08:50:38.924106+00:00] Filled 124/1000 PDFs
[2021-07-30 08:50:40.354109+00:00] Filled 125/1000 PDFs
[2021-07-30 08:50:41.675190+00:00] Filled 126/1000 PDFs
[2021-07-30 08:50:42.840879+00:00] Filled 127/1000 PDFs
[2021-07-30 08:50:44.578487+00:00] Filled 128/1000 PDFs
[2021-07-30 08:50:45.665709+00:00] Filled 129/1000 PDFs
[2021-07-30 08:50:46.734578+00:00] Filled 130/1000 PDFs
[2021-07-30 08:50:47.982121+00:00] Filled 131/1000 PDFs
[2021-07-30 08:50:49.421720+00:00] Filled 132/1000 PDFs
[2021-07-30 08:50:50.853136+00:00] Filled 133/1000 PDFs
[2021-07-30 08:50:52.586393+00:00] Filled 134/1000 PDFs
[2021-07-30 08:50:54.116911+00:00] Filled 135/1000 PDFs
[2021-07-30 08:50:55.566754+00:00] Filled 136/1000 PDFs
[2021-07-30 08:50:57.167793+00:00] Filled 137/1000 PDFs
[2021-07-30 08:50:58.517931+00:00] Filled 138/1000 PDFs
[2021-07-30 08:50:59.952412+00:00] Filled 139/1000 PDFs
[2021-07-30 08:51:01.422539+00:00] Filled 140/1000 PDFs
[2021-07-30 08:51:03.001187+00:00] Filled 141/1000 PDFs
[2021-07-30 08:51:04.200395+00:00] Filled 142/1000 PDFs
[2021-07-30 08:51:05.461275+00:00] Filled 143/1000 PDFs
[2021-07-30 08:51:06.797031+00:00] Filled 144/1000 PDFs
[2021-07-30 08:51:08.327763+00:00] Filled 145/1000 PDFs
[2021-07-30 08:51:09.844971+00:00] Filled 146/1000 PDFs
[2021-07-30 08:51:11.227019+00:00] Filled 147/1000 PDFs
[2021-07-30 08:51:12.987395+00:00] Filled 148/1000 PDFs
[2021-07-30 08:51:14.455606+00:00] Filled 149/1000 PDFs
[2021-07-30 08:51:16.234028+00:00] Filled 150/1000 PDFs
[2021-07-30 08:51:17.707512+00:00] Filled 151/1000 PDFs
[2021-07-30 08:51:19.298887+00:00] Filled 152/1000 PDFs
[2021-07-30 08:51:20.644273+00:00] Filled 153/1000 PDFs
[2021-07-30 08:51:22.380449+00:00] Filled 154/1000 PDFs
[2021-07-30 08:51:24.063020+00:00] Filled 155/1000 PDFs
[2021-07-30 08:51:25.284112+00:00] Filled 156/1000 PDFs
[2021-07-30 08:51:26.871253+00:00] Filled 157/1000 PDFs
[2021-07-30 08:51:28.242985+00:00] Filled 158/1000 PDFs
[2021-07-30 08:51:29.916709+00:00] Filled 159/1000 PDFs
[2021-07-30 08:51:31.459309+00:00] Filled 160/1000 PDFs
[2021-07-30 08:51:33.059137+00:00] Filled 161/1000 PDFs
[2021-07-30 08:51:34.517528+00:00] Filled 162/1000 PDFs
[2021-07-30 08:51:35.604907+00:00] Filled 163/1000 PDFs
[2021-07-30 08:51:37.069505+00:00] Filled 164/1000 PDFs
[2021-07-30 08:51:38.551106+00:00] Filled 165/1000 PDFs
[2021-07-30 08:51:40.078847+00:00] Filled 166/1000 PDFs
[2021-07-30 08:51:41.878719+00:00] Filled 167/1000 PDFs
[2021-07-30 08:51:43.621223+00:00] Filled 168/1000 PDFs
[2021-07-30 08:51:45.390069+00:00] Filled 169/1000 PDFs
[2021-07-30 08:51:46.653462+00:00] Filled 170/1000 PDFs
[2021-07-30 08:51:48.035451+00:00] Filled 171/1000 PDFs
[2021-07-30 08:51:49.121109+00:00] Filled 172/1000 PDFs
[2021-07-30 08:51:50.427825+00:00] Filled 173/1000 PDFs
[2021-07-30 08:51:51.785489+00:00] Filled 174/1000 PDFs
[2021-07-30 08:51:53.162364+00:00] Filled 175/1000 PDFs
[2021-07-30 08:51:54.747308+00:00] Filled 176/1000 PDFs
[2021-07-30 08:51:55.857372+00:00] Filled 177/1000 PDFs
[2021-07-30 08:51:57.632648+00:00] Filled 178/1000 PDFs
[2021-07-30 08:51:59.075826+00:00] Filled 179/1000 PDFs
[2021-07-30 08:52:00.439076+00:00] Filled 180/1000 PDFs
[2021-07-30 08:52:01.863112+00:00] Filled 181/1000 PDFs
[2021-07-30 08:52:03.298110+00:00] Filled 182/1000 PDFs
[2021-07-30 08:52:04.746830+00:00] Filled 183/1000 PDFs
[2021-07-30 08:52:06.049972+00:00] Filled 184/1000 PDFs
[2021-07-30 08:52:07.490870+00:00] Filled 185/1000 PDFs
[2021-07-30 08:52:08.875201+00:00] Filled 186/1000 PDFs
[2021-07-30 08:52:10.321934+00:00] Filled 187/1000 PDFs
[2021-07-30 08:52:11.761206+00:00] Filled 188/1000 PDFs
[2021-07-30 08:52:13.659169+00:00] Filled 189/1000 PDFs
[2021-07-30 08:52:15.138800+00:00] Filled 190/1000 PDFs
[2021-07-30 08:52:16.908119+00:00] Filled 191/1000 PDFs
[2021-07-30 08:52:18.360727+00:00] Filled 192/1000 PDFs
[2021-07-30 08:52:20.072125+00:00] Filled 193/1000 PDFs
[2021-07-30 08:52:21.139895+00:00] Filled 194/1000 PDFs
[2021-07-30 08:52:22.557270+00:00] Filled 195/1000 PDFs
[2021-07-30 08:52:23.778910+00:00] Filled 196/1000 PDFs
[2021-07-30 08:52:25.269634+00:00] Filled 197/1000 PDFs
[2021-07-30 08:52:26.619162+00:00] Filled 198/1000 PDFs
[2021-07-30 08:52:27.960556+00:00] Filled 199/1000 PDFs
[2021-07-30 08:52:29.352248+00:00] Filled 200/1000 PDFs
Traceback (most recent call last):
  ....
    file_bytes = anvil.fill_pdf(template_id, template_data)
  File ".../lib/python3.8/site-packages/python_anvil/api.py", line 72, in fill_pdf
    return api.post(
  File ".../lib/python3.8/site-packages/python_anvil/api_resources/requests.py", line 80, in post
    content, status_code, headers = self._client.request(
  File ".../lib/python3.8/site-packages/ratelimit/decorators.py", line 77, in wrapper
    raise RateLimitException('too many calls', period_remaining)
ratelimit.exception.RateLimitException: too many calls
```

**Comment by otterbotter** [comment]
Hi @aalmazan, I figured out what it is :)

The request limit period is being set in milliseconds when it should be set in seconds:
https://github.com/anvilco/python-anvil/blob/0883631172fcdd28d1eddbdf36aedf7e90e02692/python_anvil/http.py#L11

You can see on the `ratelimit` library README that it is meant to be set in seconds: https://github.com/anvilco/python-anvil/blob/0883631172fcdd28d1eddbdf36aedf7e90e02692/python_anvil/http.py#L11

So you would just need to change it from `5000` to `5` for it to enforce the rate limit described in the docs.

**Comment by aalmazan** [comment]
> The request limit period is being set in milliseconds when it should be set in seconds:

Indeed that was one problem -- thanks for digging into the issue. However, you also caught that our documentation was a little out of date as well. Our documentation page for the limits are updated now to reflect more accurate limits. I also have an upcoming PR (referenced above) that will handle retries better and fix that request limit constant mistake.

Also added in support for return HTTP header info if you'd like to handle these retries manually.

**Comment by otterbotter** [comment]
Thanks very much for the feedback @aalmazan

I sent an email to your support email address requesting a refund/reduction in our pending bill due to this bug. I explained why I think a refund is valid in this instance in the email, which I am not sure if you have visibility on or not. 

Do you know when you'll be releasing a new version of `python-anvil` which will include this fix? I'll have to wait for the fix to be merged before I can proceed with my production script.

Thanks again for your help.

**Comment by aalmazan** [comment]
@otterbotter The 0.3.0 is up on PyPI, so you should be able to update with `pip` or your preferred package manager. 

The docs are also updated, with the specific additions here: https://python-anvil.readthedocs.io/en/latest/api_usage/#supported-kwargs. 

Thanks again for the report and let me know if you have other issues!

**Comment by otterbotter** [comment]
Thanks very much @aalmazan, I was able to complete the script yesterday with no problems after updating to 0.3.0.
