### ISSUE TITLE
Anvil.fill_pdf() raises "Error: 405: None" with correct inputs

### ISSUE THREAD

**Issue by otterbotter** [anvilco/python-anvil#4]
Hey folks- thanks for putting this lib together. I've just set up an account with Anvil and found your library, so I thought I'd give it a try instead of writing my own wrapper.

I'm only trying to use the `fill_pdf` method on the `Anvil` class.

(Python 3.8)

This is my code:

```python

from python_anvil import api
from django.conf import settings

def fill_invoice():
    invoice_data = {
        ...(redacted)
        "data": {
            ...(redacted)
        },
    }

    anvil = api.Anvil(api_key="my development key")
    return anvil.fill_pdf("my template id", invoice_data)
```

Which gives me this error:

```
Traceback (most recent call last):
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/celery/app/trace.py", line 409, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/celery/app/trace.py", line 701, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/otterbotter/projects/knowalot/knowalotapp/tasks.py", line 375, in email_invoice_to_user
    invoice_pdf_bytes = pdf.generate_invoice(invoice)
  File "/home/otterbotter/projects/knowalot/knowalotapp/pdf.py", line 46, in generate_invoice
    return anvil.fill_pdf(settings.ANVIL_TEMPLATES["invoice"], invoice_data)
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/python_anvil/api.py", line 72, in fill_pdf
    return api.post(
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/python_anvil/api_resources/requests.py", line 85, in post
    return self.process_response(content, status_code, headers)
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/python_anvil/api_resources/requests.py", line 25, in process_response
    self.handle_error(response, status_code, headers)
  File "/home/otterbotter/anaconda3/envs/knowalot/lib/python3.8/site-packages/python_anvil/api_resources/requests.py", line 20, in handle_error
    raise Exception(message)
Exception: Error: 405:  None
```

405 is "Method Not Allowed", which is odd isn't it?

If you have any clue as to what the issue might be, please assist. 

Thanks kindly!

**Comment by aalmazan** [comment]
Hi @otterbotter, first off: thanks for taking the time to look at the Anvil and trying out the new API library. A fix for this is coming out shortly and should be published to PyPI today as well. Please don't hesitate to give any feedback (either good or bad!) if you have any.

**Comment by otterbotter** [comment]
Thank you @aalmazan! Updated this morning and works like a bomb.

Got my first test invoice working very easily, excited to get this into production :) 

I'm very impressed with the product so far, and the pdf filling with the templating is super cool.

Cheers.
